"""
godel.smt — emit the rulebook to SMT-LIB and let Z3 try to break each guardrail.

`disprove(rb)` asks Z3, for each guardrail: "is there ANY input that satisfies the
assumptions (and the trigger `when`) yet violates `ensures`?" `unsat` means provably no
such input; `sat` means Z3 hands back the exact counterexample.
"""
from __future__ import annotations

import re
import subprocess
import tempfile
from dataclasses import dataclass
from pathlib import Path

from .core import Bin, Call, Cmp, Expr, Fn, Ite, Lit, Rulebook, Var, _Bool


def _smt(e: Expr, defs: set[str], args: str) -> str:
    if isinstance(e, Lit):
        return str(e.val) if e.val >= 0 else f"(- {-e.val})"
    if isinstance(e, Var):
        return f"({e.name} {args})" if e.name in defs else e.name
    if isinstance(e, Call):
        return f"({e.name} " + " ".join(_smt(a, defs, args) for a in e.args) + ")"
    if isinstance(e, Bin):
        op = {"+": "+", "-": "-", "*": "*", "/": "div"}[e.op]
        return f"({op} {_smt(e.a, defs, args)} {_smt(e.b, defs, args)})"
    if isinstance(e, Cmp):
        return f"({e.op} {_smt(e.a, defs, args)} {_smt(e.b, defs, args)})"
    if isinstance(e, _Bool):
        return f"({e.op} " + " ".join(_smt(a, defs, args) for a in e.args) + ")"
    if isinstance(e, Ite):
        return f"(ite {_smt(e.cond, defs, args)} {_smt(e.a, defs, args)} {_smt(e.b, defs, args)})"
    if isinstance(e, Fn):
        a, b = _smt(e.a, defs, args), _smt(e.b, defs, args)
        return f"(ite (<= {a} {b}) {a} {b})" if e.name == "min" else f"(ite (>= {a} {b}) {a} {b})"
    raise TypeError(f"cannot emit SMT for {e!r}")


def _is_bool(e: Expr) -> bool:
    return isinstance(e, (Cmp, _Bool))


def _defs_block(rb: Rulebook) -> tuple[str, set[str]]:
    args = " ".join(rb.facts)
    names: set[str] = set()
    lines = []
    for name, e in rb.defs:
        sig = " ".join(f"({f} Int)" for f in rb.facts)
        ret = "Bool" if _is_bool(e) else "Int"
        lines.append(f"(define-fun {name} ({sig}) {ret} {_smt(e, names, args)})")
        names.add(name)
    return "\n".join(lines), names


@dataclass
class Disproof:
    guardrail: str
    safe: bool                 # True = unsat = no counterexample exists
    counterexample: str | None


def _z3(body: str) -> str:
    with tempfile.NamedTemporaryFile("w", suffix=".smt2", delete=False) as f:
        f.write(body); path = f.name
    try:
        p = subprocess.run(["z3", "-smt2", path], capture_output=True, text=True)
    finally:
        Path(path).unlink(missing_ok=True)
    return p.stdout + p.stderr


def emit(rb: Rulebook) -> str:
    """The generated SMT-LIB artifact: the function definitions, plus one disprover query
    per guardrail (each in its own push/pop scope). This is what `disprove` runs."""
    defs, names = _defs_block(rb)
    args = " ".join(rb.facts)
    decls = "\n".join(f"(declare-const {f} Int)" for f in rb.facts)
    out = [f"; generated by godel from rulebook `{rb.name}` — do not edit by hand",
           defs, decls, ""]
    for g in rb.guardrails:
        out.append(f"; guardrail {g.name}: expect `unsat` (no input breaks it)")
        out.append("(push)")
        for a in rb.assumptions:
            out.append(f"(assert {_smt(a, names, args)})")
        if g.when is not None:
            out.append(f"(assert {_smt(g.when, names, args)})")
        out.append(f"(assert (not {_smt(g.ensures, names, args)}))")
        out.append("(check-sat)")
        out.append("(pop)\n")
    return "\n".join(out)


def build(rb: Rulebook, out_smt) -> None:
    """Write the generated SMT artifact to disk."""
    from pathlib import Path
    p = Path(out_smt)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(emit(rb))


def disprove(rb: Rulebook) -> list[Disproof]:
    defs, names = _defs_block(rb)
    args = " ".join(rb.facts)
    decls = "\n".join(f"(declare-const {f} Int)" for f in rb.facts)
    results: list[Disproof] = []
    for g in rb.guardrails:
        asserts = [f"(assert {_smt(a, names, args)})" for a in rb.assumptions]
        if g.when is not None:
            asserts.append(f"(assert {_smt(g.when, names, args)})")
        asserts.append(f"(assert (not {_smt(g.ensures, names, args)}))")
        body = "\n".join([defs, decls, *asserts, "(check-sat)", "(get-model)"])
        out = _z3(body)
        if re.search(r"\bunsat\b", out):
            results.append(Disproof(g.name, True, None))
        elif re.search(r"\bsat\b", out):
            model = " ".join(l.strip() for l in out.splitlines() if l.strip() and "sat" not in l)
            results.append(Disproof(g.name, False, model[:400]))
        else:
            results.append(Disproof(g.name, False, f"z3 error: {out[:200]}"))
    return results
